version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - DATABASE_PATH=./database.sqlite
    volumes:
      - backend_uploads:/app/uploads
      - backend_db:/app
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_uploads:
  backend_db:

networks:
  app-network:
    driver: bridge 